import json
import pathlib
import ollama
from Summarizer import Summarizer 

class KeywordsDetector:
    def __init__(self, subtitle_file: str):
        """
        :param subtitle_file: Path to the JSON file containing subtitles.
        """
        self.subtitle_file = pathlib.Path(subtitle_file)
        self.data = self._load_data()

    def _load_data(self):
        try:
            with open(self.subtitle_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except FileNotFoundError:
            print(f"Error: {self.subtitle_file} not found.")
            return []
    def _build_prompt(self, current_text, generated_video_description):
            return f"""
    ### ROLE
    You are a Technical Entity Extractor. Your task is to extract keywords ONLY if they appear in the provided text.

    ### REFERENCE CONTEXT (For theme alignment only)
    "{generated_video_description}"

    ### TARGET SEGMENT (Extract from here ONLY)
    "{current_text}"

    ### STRICT EXTRACTION RULES:
    1. **SOURCE LIMITATION:** You must ONLY extract keywords that are explicitly mentioned or strongly implied within the "TARGET SEGMENT". 
    2. **NO HALLUCINATIONS:** Do NOT extract keywords from the "REFERENCE CONTEXT" if they are not in the "TARGET SEGMENT".
    3. **CONVERSATIONAL FILTER:** Ignore generic words like "video", "today", "welcome", "Adam", or "website".
    4. **EMPTY RESULT:** If the segment contains no relevant technical terms or topic-specific keywords, you MUST return an empty list [].

    ### OUTPUT FORMAT
    Return ONLY a valid JSON list of strings.
    ["keyword1", "keyword2"]
    """

    def _call_llama3(self, prompt: str) -> list:
        """Communicates with the local Llama model via Ollama."""
        try:
            response = ollama.generate(
                model="llama3.1:latest", 
                prompt=prompt,
                format="json",
                options={"temperature": 0.1}
            )
            
            result = json.loads(response['response'])
            
            if isinstance(result, dict):
                for key in ["keywords", "terms", "tags", "result"]:
                    if key in result: return result[key]
                return list(result.values())[0] if result else []
            
            return result if isinstance(result, list) else []
            
        except Exception as e:
            print(f"Llama 3.1 Error: {e}")
            return []

    def process_with_summary(self, summary_sentences: int = 3, output_name: str = None):
        """
        Extracts keywords where the 'video_description' is automatically 
        generated by the Summarizer class.
        """
        if output_name is None:
            output_name = f"{self.subtitle_file.stem}_auto_enriched.json"

        # --- STEP 1: Generate the description automatically ---
        print(f"--- Step 1: Generating Auto-Description ({summary_sentences} sentences) ---")
        summarizer = Summarizer(str(self.subtitle_file))
        summary_results = summarizer.get_summary(sentence_count=summary_sentences)
        
        # This is now our 'video_description'
        auto_description = " ".join([str(s) for s in summary_results])
        
        print(f"Generated Description: {auto_description}\n")

        # --- STEP 2: Keyword Extraction ---
        final_output = []
        total_segments = len(self.data)

        print(f"--- Step 2: Processing {total_segments} segments with Llama 3.1 ---")
        
        for i, entry in enumerate(self.data):
            text_segment = entry.get("text", "").strip()
            
            if len(text_segment) > 3:
                # Use the auto_description as the context for every segment
                prompt = self._build_prompt(text_segment, auto_description)
                detected_keywords = self._call_llama3(prompt) 
            else:
                detected_keywords = []
            
            new_record = {
                **entry,
                "keywords": detected_keywords,
                "have_keywords": bool(detected_keywords)
            }
            
            final_output.append(new_record)
            
            if (i + 1) % 10 == 0 or (i + 1) == total_segments:
                print(f"Progress: {i + 1}/{total_segments} analyzed.")

        # --- STEP 3: Save results ---
        with open(output_name, "w", encoding="utf-8") as f:
            json.dump(final_output, f, indent=4, ensure_ascii=False)

        print(f"\nProcessing complete! Enriched file saved as: {output_name}")
        return final_output

# --- Usage ---
if __name__ == "__main__":
    # No need to provide a manual description anymore!
    detector = KeywordsDetector("../tests/test_subtitles.json")
    
    # Just run it. The class will 'describe' the video to the LLM itself.
    detector.process_with_summary(summary_sentences=4)